properties(
 [
  parameters (
    [
    booleanParam(name: 'wait', defaultValue: false, description: 'Wait for plan to finish'),
    string(name: 'kcli-config-yml', defaultValue: "kcli-config-yml", description: 'Secret File Credential storing your ~/.kcli/config.yml'),
    string(name: 'kcli-id-rsa', defaultValue: "kcli-id-rsa", description: 'Secret File Credential storing your private key'),
    string(name: 'kcli-id-rsa-pub', defaultValue: "kcli-id-rsa-pub", description: 'Secret File Credential container your public key'),
    string(name: 'prefix', defaultValue: "prout", description: ''),
    string(name: 'image', defaultValue: "CentOS-7-x86_64-GenericCloud.qcow2", description: ''),
    string(name: 'pool', defaultValue: "default", description: ''),
    string(name: 'network', defaultValue: "default", description: '')
    ]
  )
 ]
)

pipeline {
    agent {
        kubernetes {
      cloud 'openshift'
      label 'kcli'
      serviceAccount 'default'
      defaultContainer 'kcli'
      yaml """
apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: kcli
    image: docker.io/karmab/kcli:latest
    command: ['kweb']
    tty: true
"""
        }
    }
    stages {
        stage('Prepare kcli environment') {
            steps {
                sh '''
                echo proutos
                '''
            }
        }
    }
}
