properties(
 [
  parameters (
    [
    booleanParam(name: 'wait', defaultValue: false, description: 'Wait for plan to finish'),
    string(name: 'kcli-config-yml', defaultValue: "kcli-config-yml", description: 'Secret File Credential storing your ~/.kcli/config.yml'),
    string(name: 'kcli-id-rsa', defaultValue: "kcli-id-rsa", description: 'Secret File Credential storing your private key'),
    string(name: 'kcli-id-rsa-pub', defaultValue: "kcli-id-rsa-pub", description: 'Secret File Credential container your public key'),
    string(name: 'prefix', defaultValue: "prout", description: ''),
    string(name: 'image', defaultValue: "CentOS-7-x86_64-GenericCloud.qcow2", description: ''),
    string(name: 'pool', defaultValue: "default", description: ''),
    string(name: 'network', defaultValue: "default", description: ''),
    ]
  )
 ]
)

pipeline {
    agent { kubernetes {
      cloud 'openshift'
      label 'kcli'
      serviceAccount 'default'
      yaml """
apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: kcli
    image: docker.io/karmab/kcli:latest
    command: ['kweb']
    tty: true
"""
          }
    }
    environment {
     KCLI_CONFIG = credentials("${params.kcli_config_yml}")
     KCLI_SSH_ID_RSA = credentials("${params.kcli_id_rsa}")
     KCLI_SSH_ID_RSA_PUB = credentials("${params.kcli_id_rsa_pub}")
     KCLI_PARAMETERS = "-P prefix=${params.prefix} -P image=${params.image} -P pool=${params.pool} -P network=${params.network}"
     CONTAINER_OPTIONS = "--net host --rm --security-opt label=disable -v $HOME/.kcli:/root/.kcli -v $HOME/.ssh:/root/.ssh -v $PWD:/workdir -v /var/tmp:/ignitiondir"
     KCLI = "kcli"
    }
    stages {
        stage('Prepare kcli environment') {
            steps {
                container('kcli') {
                sh '''
                [ -d $HOME/.kcli ] && rm -rf $HOME/.kcli
                mkdir $HOME/.kcli
                cp "$KCLI_CONFIG" $HOME/.kcli/config.yml
                cp "$KCLI_SSH_ID_RSA" $HOME/.kcli/id_rsa
                cp "$KCLI_SSH_ID_RSA_PUB" $HOME/.kcli/id_rsa.pub
                '''
                }
            }
        }
    }
}
